language: cpp
sudo: required

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
      env:
        - MATRIX_EVAL="CC=clang-4.0 && CXX=clang++-4.0"
        
before_install:
    - eval "${MATRIX_EVAL}"
    - wget http://www.cmake.org/files/v3.9/cmake-3.9.0-Linux-x86_64.sh
    - sudo sh cmake-3.9.0-Linux-x86_64.sh --skip-license --prefix=/usr
# Build steps

script:
- sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
- sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
- gcc -v && g++ -v && cmake --version

- mkdir build
- cd build
- cmake .. 
- make
- ./bin/exe/math_test
