# version format
version: 0.0.1.{build}

environment:
  matrix:
    - compiler: msvc-15-seh
      generator: "Visual Studio 15 2017"

    - compiler: msvc-14-seh
      generator: "Visual Studio 14 2015"

platform:
  - x64
 
configuration:
  - Release
  - Debug

install:
    - git submodule update --init --recursive

before_build:
    - cmake -G "$env:generator"

build:
  project: $(APPVEYOR_BUILD_FOLDER)\Project.sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\bin\exe\%CONFIGURATION%\math_test.exe'