# version format
version: 0.0.1.{build}

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      generator: "Visual Studio 15 2017 Win64"

    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      generator: "Visual Studio 14 2015 Win64"

platform:
  - x64
 
configuration:
  - Release
  - Debug

install:
    - git submodule update --init --recursive

before_build:
    - cmake -G "$(generator)"

build:
  project: $(APPVEYOR_BUILD_FOLDER)\Project.sln

test_script:
  - '%APPVEYOR_BUILD_FOLDER%\bin\exe\%CONFIGURATION%\math_test.exe'