# This file is part of Tempest-math project
# Author: Karol Kontny

set(TEMPEST_CODE ${TEMPEST_CODE} ${CMAKE_SOURCE_DIR}/src/tstmath.h)
set(TEMPEST_CODE ${TEMPEST_CODE} ${CMAKE_SOURCE_DIR}/src/assert.h)
set(TEMPEST_CODE ${TEMPEST_CODE} ${CMAKE_SOURCE_DIR}/src/util.h)
set(TEMPEST_CODE ${TEMPEST_CODE} ${CMAKE_SOURCE_DIR}/src/config.h)
set(TEMPEST_CODE ${TEMPEST_CODE} ${CMAKE_SOURCE_DIR}/src/vec.h)
set(TEMPEST_CODE ${TEMPEST_CODE} ${CMAKE_SOURCE_DIR}/src/vec4.h)
set(TEMPEST_CODE ${TEMPEST_CODE} ${CMAKE_SOURCE_DIR}/src/vec4.inl)

source_group(TREE ${CMAKE_SOURCE_DIR}/src FILES ${TEMPEST_CODE})

set(TEMPEST_CODE ${TEMPEST_CODE} PARENT_SCOPE)